import { ai, primaryModel } from '../config/genkit.js';
import {
  ReceiptInputSchema,
  RawExpenseOutputSchema,
  ExpenseOutputSchema,
  type ReceiptInput,
  type ExpenseOutput,
} from '../schemas/expense.schema.js';
import { validateAndSanitizeReceipt } from '../validators/receipt.validator.js';

function buildExtractionPrompt(imageUrl: string, preferredCurrency: string) {
  return [
    { media: { url: imageUrl } },
    {
      text: `You are an expert financial assistant specialized in analyzing receipts and extracting structured expense information.

Analyze the provided receipt image carefully and extract all relevant details:
1. merchantName: Identify the store, vendor, restaurant, or business name.
2. totalAmount: Extract the grand total charged/paid (as a positive number).
3. currency: Detect the currency (e.g. USD, EUR, GBP, etc.). If not visible, use "${preferredCurrency}".
4. date: Extract the transaction date in YYYY-MM-DD format. If year is missing or ambiguous, use the best estimated date.
5. category: Classify the expense into exactly one of the following categories:
   - "Food & Dining", "Groceries", "Transportation", "Entertainment", "Utilities", "Shopping", "Travel", "Other"
6. items: Extract individual purchased items with name, price, and quantity when available.
7. tax: Extract sales tax / VAT if listed.
8. confidence: Assess whether extraction confidence is "high", "medium", or "low" based on receipt clarity.
9. summary: Provide a concise one-line summary (e.g., "Lunch at Chipotle").

CRITICAL GUARDRAILS:
- If the image is blurry, unreadable, dark, occluded, or does not clearly display text/numbers:
  * Do NOT guess, fabricate, or hallucinate store names, prices, or line items.
  * Set "confidence" to "low".
  * Set "merchantName" to "Unreadable Receipt".
  * Set "totalAmount" to 0 (or only extract strictly legible numbers).
  * Leave "items" as an empty list [].
  * In "summary", explain: "Receipt image is too blurry or unclear to read reliably."`,
    },
  ];
}

/**
 * Checkpoint 03: Validation & Sanitization Flow
 * - Builds on Checkpoint 02's structured output
 * - Adds anti-hallucination prompt guardrails for blurry images
 * - Pipes raw extraction through business rules validation & sanitization
 * - Adds math reconciliation, currency normalization, and validation warnings
 */
export const extractReceiptFlow = ai.defineFlow(
  {
    name: 'extractReceiptFlow',
    inputSchema: ReceiptInputSchema,
    outputSchema: ExpenseOutputSchema,
  },
  async (input: ReceiptInput): Promise<ExpenseOutput> => {
    const { imageUrl, preferredCurrency = 'USD' } = input;
    const prompt = buildExtractionPrompt(imageUrl, preferredCurrency);

    const response = await ai.generate({
      model: primaryModel,
      prompt,
      config: {
        temperature: 0.0,
      },
      output: {
        schema: RawExpenseOutputSchema,
      },
    });

    if (!response.output) {
      throw new Error('No structured output generated by AI model.');
    }

    // Apply defensive validation and business rule sanitization
    const validatedExpense = validateAndSanitizeReceipt(response.output, {
      preferredCurrency,
    });

    return validatedExpense;
  }
);
