import { ai, primaryModel } from '../config/genkit.js';
import {
  ReceiptInputSchema,
  RawExpenseOutputSchema,
  type ReceiptInput,
  type RawExpenseOutput,
} from '../schemas/expense.schema.js';

function buildExtractionPrompt(imageUrl: string, preferredCurrency: string) {
  return [
    { media: { url: imageUrl } },
    {
      text: `You are an expert financial assistant specialized in analyzing receipts and extracting structured expense information.

Analyze the provided receipt image carefully and extract all relevant details:
1. merchantName: Identify the store, vendor, restaurant, or business name.
2. totalAmount: Extract the grand total charged/paid (as a positive number).
3. currency: Detect the currency (e.g. USD, EUR, GBP, etc.). If not visible, use "${preferredCurrency}".
4. date: Extract the transaction date in YYYY-MM-DD format.
5. category: Classify the expense into one of: "Food & Dining", "Groceries", "Transportation", "Entertainment", "Utilities", "Shopping", "Travel", "Other".
6. items: Extract individual purchased items with name, price, and quantity when available.
7. tax: Extract sales tax / VAT if listed.
8. confidence: Assess whether extraction confidence is "high", "medium", or "low" based on receipt clarity.
9. summary: Provide a concise one-line summary (e.g., "Lunch at Chipotle").`,
    },
  ];
}

/**
 * Checkpoint 02: Structured Output Flow
 * - Enforces Zod output schema directly on Gemini
 * - Deterministic temperature 0.0
 * - Eliminates regex and JSON parsing errors
 */
export const extractReceiptFlow = ai.defineFlow(
  {
    name: 'extractReceiptFlow',
    inputSchema: ReceiptInputSchema,
    outputSchema: RawExpenseOutputSchema,
  },
  async (input: ReceiptInput): Promise<RawExpenseOutput> => {
    const { imageUrl, preferredCurrency = 'USD' } = input;
    const prompt = buildExtractionPrompt(imageUrl, preferredCurrency);

    const response = await ai.generate({
      model: primaryModel,
      prompt,
      config: {
        temperature: 0.0, // deterministic sampling
      },
      output: {
        schema: RawExpenseOutputSchema, // Schema-enforced structured output
      },
    });

    if (!response.output) {
      throw new Error('No structured output generated by AI model.');
    }

    return response.output;
  }
);
